@host = http://localhost:3000
@api = http://localhost:3000/api/v1/tasks

###
GET {{host}}/hello

### getAllTasks
GET {{api}}

### createTask
POST {{api}}
Content-Type: application/json

{
	"name": "Completed task",
	"completed": true
}
### Get Single Task
GET {{api}}/618bd800f9ff9f8a85748ea8
###
PATCH {{api}}/618bd800f9ff9f8a85748ea8
Content-Type: application/json

{
	"name": "Updating some things",
	"completed": true
}

### deleteTask
DELETE {{api}}/619281f2bbb7488488b41907
