@host = http://localhost:3000
@api = http://localhost:3000/api/v1/tasks

###
GET {{host}}/hello

### gtAllTasks
GET {{api}}

### createTask
POST {{api}}
Content-Type: application/json

{
	"name": "shake and bake",
	"completed": true
}
### Get Single Task
GET {{api}}/peter
###
PATCH {{api}}/1
Content-Type: application/json

{
	"name": "shake and bake",
	"completed": true
}

###
DELETE {{api}}/1