@host = http://localhost:3000
@api = http://localhost:3000/api/v1/tasks

###
GET {{host}}/hello

### getAllTasks
GET {{api}}

### createTask
POST {{api}}
Content-Type: application/json

{
	"name": "server still running",
	"completed": false
}
### Get Single Task
GET {{api}}/618bd800f9ff9f8a85748ea8
###
PATCH {{api}}/618bd800f9ff9f8a85748ea8
Content-Type: application/json

{
	"name": "testing edit",
	"completed": false
}

### deleteTask
DELETE {{api}}/618938b8c44d1572d426986c